# This is a basic workflow to help you get started with Actions

name: Long

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  SleepForLong:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: ./Sleep8hours.sh
