name: Long Sleep

on:
  workflow_dispatch:
jobs:
  SleepForLong:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          chmod +x ./Sleep8hours.sh
          ./Sleep8hours.sh
